---
grails:
    profile: web
    codegen:
        defaultPackage: cn.edu.bnuz.bell
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: applicationForm/atom+xml
            css: text/css
            csv: text/csv
            form: applicationForm/x-www-form-urlencoded
            html:
              - text/html
              - applicationForm/xhtml+xml
            js: text/javascript
            json:
              - applicationForm/json
              - text/json
            multipartForm: multipart/form-data
            pdf: applicationForm/pdf
            rss: applicationForm/rss+xml
            text: text/plain
            hal:
              - applicationForm/hal+json
              - applicationForm/hal+xml
            xml:
              - text/xml
              - applicationForm/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
server:
    port: 23310

spring:
    application:
        name: ${info.app.name}

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

security:
    oauth2:
        resource:
            userInfoUri: http://localhost/uaa/user

bell:
    student:
        filesPath: 'D:\temp\tm'
